CREATE TABLE `mydb`.`user`(  
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(200) NOT NULL,
  `PASSWORD` VARCHAR(300) NOT NULL,
  `EMAIL` VARCHAR(300),
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `IDX_USERNAME` (`USER_NAME`)
) ENGINE=INNODB;
